apiVersion: batch/v1
kind: Job
metadata:
  name: mysqlslap
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: mysqlslap
        image: mysqlslap:v1
        imagePullPolicy: Never
      restartPolicy: Never
