apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      volumes:
      - name: php-pv-storage
        persistentVolumeClaim:
          claimName: php-pv-claim
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
           - key: config
             path: site.conf
      containers:
        - name: nginx
          image: nginx:1.9.1
          ports:
           - containerPort: 80
          volumeMounts:
            - name: php-pv-storage
              mountPath: /data
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
