apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      containers:
      - name: php
        image: arnnow/k8s-nginx-php:latest
        volumeMounts:
        - mountPath: /data
          name: php-pv-storage
      volumes:
      - name: php-pv-storage
        persistentVolumeClaim:
          claimName: php-pv-claim
