apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      containers:
      - name: php
        image: php:7-fpm
        volumeMounts:
        - mountPath: /data
          name: php-pv-storage
      volumes:
      - name: php-pv-storage
        persistentVolumeClaim:
          claimName: php-pv-claim
      initContainers:
        - name: install
          image: busybox
          volumeMounts:
          - name: php-pv-storage
            mountPath: /code
          command: ['wget','-O','/code/guestbook.php','https://raw.githubusercontent.com/arnnow/k8s-nginx-php/master/files/guestbook.php']
        - name: install1
          image: busybox
          volumeMounts:
          - name: php-pv-storage
            mountPath: /code
          command: ['wget','-O','/code/index.html','https://raw.githubusercontent.com/arnnow/k8s-nginx-php/master/files/index.html']
        - name: install2
          image: busybox
          volumeMounts:
          - name: php-pv-storage
            mountPath: /code
          command: ['wget','-O','/code/controllers.js','https://raw.githubusercontent.com/arnnow/k8s-nginx-php/master/files/controllers.js']
        - name: install3
          image: busybox
          volumeMounts:
          - name: php-pv-storage
            mountPath: /code
          command: ['wget','-O','/code/index.php','https://raw.githubusercontent.com/arnnow/k8s-nginx-php/master/files/index.php']
